using Microsoft.Agents.AI;

namespace Agent200.Host.Services;

/// <summary>
/// Interface for the Tier 3 Fixer Agent.
/// Responsible for automated remediation of infrastructure issues by creating GitHub Pull Requests.
/// </summary>
public interface IFixerAgent
{
    /// <summary>
    /// Executes the remediation process based on the provided Root Cause Analysis (RCA).
    /// </summary>
    /// <param name="rcaReport">The detailed RCA report generated by the Investigator Agent.</param>
    /// <returns>A summary of the remediation actions taken (e.g., "PR created: https://github...").</returns>
    Task<string> RemediateAsync(string rcaReport);

    /// <summary>
    /// Returns the underlying AIAgent instance for use in workflows.
    /// </summary>
    AIAgent AsAgent();
}
